name: Golden AMI test

on:
  repository_dispatch:
      types: [integration-event]

jobs:
  Update-Golden-AMI:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        actions: write
    steps:
    - uses: actions/checkout@v4
    - run: 'echo "field: ${{ github.event.client_payload.previousAMI }}"'
    - run: 'echo "field: ${{ github.event.client_payload.createdAMI }}"'
    - run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'    
