name: Golden AMI test

on:
  repository_dispatch:
      types: [integration-event]
  workflow_dispatch:    

jobs:
  Update-Golden-AMI:
    runs-on: ubuntu-latest
    permissions:
        contents: write
        pull-requests: write
        actions: write
    steps:
    - uses: actions/checkout@v4
    #- run: 'echo "field Previous AMI: ${{ github.event.client_payload.previousAMI }}"'
    #- run: 'echo "field Created AMI: ${{ github.event.client_payload.createdAMI }}"'
    #- run: 'echo "payload: ${{ toJson(github.event.client_payload) }}"'    
    
    - name: get current time
      id: current_time
      uses: Kaven-Universe/github-action-current-date-time@v1
      with:
        format: "YYYY_MM_DD"

    #- name: Create new branch
    #  id: create_branch
    #  env:
    #    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    #  run: |
    #    git branch automation/updateAMI-${{ steps.current_time.outputs.time }}-${{ github.repository }}
    #    git checkout automation/updateAMI-${{ steps.current_time.outputs.time }}-${{ github.repository }}

    - name: Replace old AMI value with new one.
      uses: jacobtomlinson/gha-find-replace@v3
      with:
        find: pepe2  
        replace: moka
        include: "**"
        regex: false
          
    - name: Create Pull Request  
      id: create_PR
      uses: peter-evans/create-pull-request@v6
      with:
          git-token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: Newly created AMI from AWS SSM
          title: New AMI and SNAPSHOT values from AWS SSM
          body: New AMI and SNAPSHOT values from AWS SSM
          branch: automation/updateAMI-${{ steps.current_time.outputs.time }}-${{ github.repository }}  #branch where you commit
          base: main                              
          #reviewers: DevOps   
          draft: false   
